---
- name: Enable Windows Update service
  win_service:
    name: wuauserv
    start_mode: auto
    state: started

- name: Configure RDP port to 7379
  win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
    name: PortNumber
    data: 7379
    type: dword

- name: Allow RDP 7379 in firewall
  win_firewall_rule:
    name: RDP-7379
    localport: 7379
    protocol: TCP
    direction: Inbound
    action: Allow

- name: Allow SNMP UDP 161-162 from PRTG server
  win_firewall_rule:
    name: SNMP-161-162
    localport: 161-162
    protocol: UDP
    direction: Inbound
    action: Allow
    remoteip: 52.71.181.46

- name: Install SNMP feature
  win_feature:
    name: SNMP-Service
    state: present

- name: Configure SNMP community (read-only)
  win_shell: |
    $snmp = Get-WmiObject -Namespace root\cimv2 -Class Win32_Service -Filter "Name='SNMP'"
    if ($snmp) {
      # Use a placeholder community name; replace in your environment
      sc.exe config SNMP start= auto
    }

- name: Allow FTP ports 21, 30000-35000
  win_firewall_rule:
    name: FTP-21
    localport: 21
    protocol: TCP
    direction: Inbound
    action: Allow

- name: Allow FTP passive ports 30000-35000
  win_firewall_rule:
    name: FTP-Passive
    localport: 30000-35000
    protocol: TCP
    direction: Inbound
    action: Allow

- name: Set Date/Time and TimeZone
  win_timezone:
    timezone: "India Standard Time"  # Change if needed
  register: tz

- name: Stop Windows Search service
  win_service:
    name: WSearch
    state: stopped
    start_mode: disabled

- name: Change hostname
  win_hostname:
    name: "postiefs"  # <-- replace with desired hostname

- name: Create users (placeholders)
  win_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    groups: "{{ item.groups | default([]) }}"
    state: present
  loop:
    - { name: "ptpladmin", password: "{{ lookup('env','Ka1234*#') }}", groups: ['Administrators','Remote Desktop Users'] }
    - { name: "postiefssupport", password: "{{ lookup('env','Ka1234*#') }}", groups: ['Administrators','Remote Desktop Users'] }
    

- name: Install Google Chrome
  win_chocolatey:
    name: googlechrome
    state: present

- name: Install 7-Zip
  win_chocolatey:
    name: 7zip
    state: present

- name: Install FileZilla
  win_chocolatey:
    name: filezilla
    state: present

- name: Install Microsoft Edge
  win_chocolatey:
    name: microsoft-edge
    state: present

- name: Reboot to apply changes
  win_reboot:
    msg: "Rebooting after hardening and software installation"
    pre_reboot_delay: 5
